### ISSUE TITLE
System Monitor stats page is empty

### ISSUE THREAD

**Issue by jansol** [nix-community/kde2nix#6]
This line in the journal seems relevant.
```
plasma-systemmonitor[21359]: org.kde.ksysguard.plugin.network: Helper process terminated abnormally: "The process doesn't have permission to open the capture source"
```

**Comment by K900** [comment]
Fixed, turns out ksystemstats is still required.

**Comment by jansol** [comment]
Hmm.... Memory, Network and Disk I/O look about right now but CPU shows almost 0% while rebuilding all of KDE and htop showing that all cores are pinned to 100%.

**Comment by K900** [comment]
Weird. Works fine here.

**Comment by jansol** [comment]
It's funny, it seems to only affect `nixos-rebuild build`

**Comment by jansol** [comment]
![image](https://github.com/nix-community/kde2nix/assets/2588851/8cf7bdff-097c-410a-955d-79cbbeef4597)
still happens, also with `nix run` (when it has to build the thing to be run first)

**Comment by K900** [comment]
Could be https://invent.kde.org/plasma/ksystemstats/-/merge_requests/65 as suggested on Matrix. @jansol can you test with this applied?

**Comment by jansol** [comment]
What would be the easiest way to apply that to this flake? Just cloning the repo and adding the patch there?

**Comment by K900** [comment]
Thanks, picked the patch.
